[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py
testpaths = edu_modules/tests
addopts =
    --ds=config.settings
    --cov=edu_modules
    --cov-report=term-missing
    -v
norecursedirs =
    .venv
    migrations
    __pycache__
    .git
    .idea