# Generated by Django 5.2.3 on 2025-07-01 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Число от 1 до 1000', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Порядковый номер')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('status', models.CharField(choices=[('DF', 'Черновик'), ('PB', 'Опубликован'), ('AR', 'Архивный')], default='DF', max_length=2, verbose_name='Статус')),
                ('duration_hours', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Длительность (часы)')),
            ],
            options={
                'verbose_name': 'Образовательный модуль',
                'verbose_name_plural': 'Образовательные модули',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('order',), name='unique_module_order')],
            },
        ),
    ]
