# Generated by Django 5.2.3 on 2025-07-06 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalmodule',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Полное описание содержания модуля', verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='educationalmodule',
            name='duration_hours',
            field=models.PositiveSmallIntegerField(default=0, help_text='Общая продолжительность обучения в часах (макс. 500)', validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Длительность (часы)'),
        ),
        migrations.AlterField(
            model_name='educationalmodule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Доступен ли модуль для использования', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='educationalmodule',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Уникальный порядковый номер от 1 до 1000', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='educationalmodule',
            name='status',
            field=models.CharField(choices=[(None, '(Не указано)'), ('DF', 'Черновик'), ('PB', 'Опубликован'), ('AR', 'Архивный')], default='DF', help_text='Статус публикации модуля', max_length=2, verbose_name='Текущий статус'),
        ),
        migrations.AlterField(
            model_name='educationalmodule',
            name='title',
            field=models.CharField(help_text='Полное название образовательного модуля', max_length=255, unique=True, verbose_name='Название модуля'),
        ),
        migrations.AddConstraint(
            model_name='educationalmodule',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_module_title', violation_error_message='Модуль с таким названием уже существует'),
        ),
        migrations.AlterConstraint(
            model_name='educationalmodule',
            name='unique_module_order',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_module_order', violation_error_message='Порядковый номер должен быть уникальным'),
        ),
    ]
