# Generated by Django 5.2.3 on 2025-07-06 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_modules', '0002_alter_educationalmodule_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalmodule',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Пользователь, создавший этот модуль', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_modules', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
